# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: GetConjurSecret@1
  inputs:
    conjurapplianceurl: 'https://dapmaster.cybr.com'
    conjuraccount: 'cyberark'
    conjurusername: 'host/pipeline-consumers/agent01'
    conjurapikey: '$(conjurkey1)'
    ignoreSsl: true
    secretsyml: secrets.yml

- script: echo $(SqlServerName) $(SqlToken)


- task: AzurePowerShell@4
  inputs:
    #azureSubscription: my-arm-service-connection
    scriptType: filePath
    scriptPath: $(Build.SourcesDirectory)\helloworld.ps1
    #scriptArguments:
    #  -Arg1 val1 `
    #  -Arg2 val2 `
    #  -Arg3 val3
    azurePowerShellVersion: latestVersion
